(exception_type)(func throw 0 throw 0 throw 0=)