(exception_type $b)(func rethrow $$ rethrow $try rethrow $tr rethrow $tnc rethrow $$ rethrow $try rethrow $tr rethrow $tr$ rethrow $ry rethrow $t rethrow $t rethrow $tr$ rethrow $ry rethrow $t rethrow $t rethrow $t.y)