(module(exception_type $b)(func  try catch $b end))