(module (exception_type $b)(func  try  catch $b catch $b catch $b catch $b catch $b catch  $b  end))